# Generated by Django 3.1.2 on 2020-10-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201021_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='image3',
        ),
    ]
